# these will be read from the OS environment variables

# Google Oauth2
#  create the Google Oauth2 parameters through this Google URL:
# https://console.cloud.google.com/apis/credentials
GOOGLE_OAUTH2_CLIENTID: ${GOOGLE_OAUTH2_CLIENTID}
GOOGLE_OAUTH2_CLIENTSECRET: ${GOOGLE_OAUTH2_CLIENTSECRET}
GOOGLE_OAUTH2_CALLBACK: ${GOOGLE_OAUTH2_CALLBACK}
# session cookie store
# Note: Don't store your key in your source code. Pass it via an environmental variable, or flag (or both), 
# and don't accidentally commit it alongside your code. Ensure your key is sufficiently random 
# i.e. use Go's crypto/rand or securecookie.GenerateRandomKey(32) and persist the result.
COOKIE_STORE_SECRET: ${COOKIE_STORE_SECRET}